### ISSUE TITLE
possible to convert these clock readings to a time? 

### ISSUE THREAD

**Issue by jonathanstrong** [brayniac/clocksource#10]
hey - 

Perhaps this should be obvious but to me it is not. How can I convert these clock readings to represent the number of nanoseconds since 1970? Is that possible? Perhaps they are only for timing things but would be nice to get a more precise and fast time out of it as part of the same deal. 

Thanks!

**Comment by brayniac** [comment]
Hi @jonathanstrong - right now the library is targeting the use-case of relative timing - like the duration between two instants. I also anticipate the relative timescale to be short - and that minor error due to potentially inaccurate calibration of TSC in relation to the system clock is inconsequential. 

Getting precise timing that follows UTC is tricky. Leap seconds need to be factored it and you may run into the need for doing some active steering of the clock to maintain both frequency (duration of a second) and phase (when exactly a second began) lock over time. When we use the system clock - eg ```clock_gettime(CLOCK_REALTIME)``` - this has all (hopefully) been handled correctly by the kernel and NTP. 

Another important thing to realize is that the TSC is only useful when the processor guarantees that the frequency of the TSC does not change and that the TSC does not stop incrementing (eg: due to powersave). When these can't be guaranteed - we can only really make use of ```clock_gettime(CLOCK_MONOTONIC)```.

If you wanted to try getting ```clock_gettime(CLOCK_REALTIME)``` **estimators** from clocksource (using the TSC as reference) - it's probably possible to just patch https://github.com/brayniac/clocksource/blob/master/src/lib.rs#L104 to use CLOCK_REALTIME - however, this clock may be subject to jumps (either forward or backward) and this library is **NOT** designed to handle that.

Let me know if you have further questions.

**Comment by jonathanstrong** [comment]
Thanks for your help on this! I did verify I can rely on my TSC (xeons from a few generations ago) to remain at the same frequency from an article I read introducing what the TSC is. Also don't plan on using this for something sensitive to jumps (i.e. has x time elapsed) but rather to timestamp messages and the like that are coming in at a rate of hundreds of times a second. `chrono::Utc::now()` takes ~45 ns on my machines which is not a lot but when you are doing it over and over it seems like an ~8 ns alternative might be worth it. Fwiw system is Ubuntu 16.04.

Just to make sure I am understanding your suggestion, are you saying I should use the calibrated time from clocksource to pass to libc, i.e.

```
let mut clock = clocksource::Clocksource::new();
clock.calibrate();
let t = clock.time();
let spec = convert_to_timespec(t); // unimplmented fn (t: u64) -> libc::timespec
libc::clock_gettime(libc::CLOCK_REALTIME, &mut spec);
```

I expect this is wrong in fairly obvious ways but keep in mind I have not previously had occasion to directly call the system time functions in my code! 

Thanks again for your help - and for providing the library. I am also using some of your other work as well (shuteye) and it seems you must find minute fractions of time as fascinating as I do, albeit from a perch of much greater expertise.

**Comment by brayniac** [comment]
@jonathanstrong - sorry if I wasn't entirely clear - the change that would need to be made, would be to the clocksource code itself. Clone the repo, make the change locally, and point to your locally modified version. Changing its reference from CLOCK_MONOTONIC to CLOCK_REALTIME should cause it to give estimates in ns since unix epoch if I understand correctly. I might have some bandwidth over the weekend to look at this myself.

**Comment by brayniac** [comment]
@jonathanstrong - checkout the branch "realtime" https://github.com/brayniac/clocksource/tree/realtime - I've applied the patch I was suggesting, it passes tests, but I won't have time to analyze the behavior more fully today. You should just be able to point Cargo.toml to this git repo with the "realtime" branch and test it out. 

Let me know if it seems useful - you will need to pay the conversion cost somewhere - clocksource.time() is automagically converted during the call - or you can do .counter() and .convert() separately (eg - if you timestamp in critical section of the code, it might make sense to .convert() after the fact or in a separate aggregating thread).

**Comment by brayniac** [comment]
I've updated the branch again - there's now an example which can give you a sense of the stability of the clock. I'm using Time Deviation for this: https://en.wikipedia.org/wiki/Time_deviation

```
$ cargo run --example clock --features rdtsc --release
```

Output will be like:
```
Calculating stability of time estimators... runtime ~15 minutes
Baseline:
Reference: Monotonic Source: Monotonic
Stability:
     TDEV(1mS): 2.143e-7
    TDEV(10mS): 2.145e-7
   TDEV(100mS): 2.149e-7
      TDEV(1S): 2.171e-7
     TDEV(10S): 2.296e-7
    TDEV(100S): 2.392e-7
Realtime:
Reference: Realtime Source: Counter
Stability:
     TDEV(1mS): 3.478e-7
    TDEV(10mS): 3.481e-7
   TDEV(100mS): 3.488e-7
      TDEV(1S): 3.523e-7
     TDEV(10S): 3.596e-7
    TDEV(100S): 4.648e-7
Monotonic:
Reference: Monotonic Source: Counter
Stability:
     TDEV(1mS): 2.611e-7
    TDEV(10mS): 2.640e-7
   TDEV(100mS): 2.697e-7
      TDEV(1S): 3.033e-7
     TDEV(10S): 3.490e-7
    TDEV(100S): 3.681e-7
```

You can see that both the clocks which used the Counter source exhibit some phase instability at 100 second timescales - error is ~465ns at 100s for the Realtime clock - and ~368ns at 100s for the monotonic clock. Note - for the Monotonic<->Monotonic baseline - we see about ~215ns error consistenty (likely due to the system call to get the time with some jitter). 

Expect this TDEV for the realtime estimator to grow over even longer timescales. If your use-case involves time-stamping across wide timeframes - it may be necessary to periodically call `.calibrate()` on the `Clocksource`. Note this is a blocking call - takes about 1 second. But this can help maintain better phase lock over longer runtimes by syncing to the reference clock again. The `recalibrate()` method would help more with frequency being incorrect than with phase - so you'll need to take penalty of the 1S calibration time periodically. You might be able to do this in a separate thread and swap with the recalibrated clocksource. the clocksource. I'm not sure if that would be great for "deferred conversion" - the flow which uses `.counter()` and separately `.convert()`  - but should be fine if you're always using `.time()`.

**Comment by jonathanstrong** [comment]
Very cool. I think this will be the fastest way to timestamp something available!

Thanks for your detailed advice on periodically calibrating it. In my case it's never convenient to wait a full second but it's very easy to have another thread sending newly calibrated clocks to the "hot path" threads every so often. Do you see any problem with cloning a newly calibrated clock to send to many worker threads? 

For reference, here are the readings from the example script on my laptop at home and a production server:

#### Laptop: i7-3630QM @ 2.40GHz 
```
Calculating stability of time estimators... runtime ~15 minutes
Baseline:
Reference: Monotonic Source: Monotonic
Stability:
     TDEV(1mS): 1.086e-6
    TDEV(10mS): 1.089e-6
   TDEV(100mS): 1.092e-6
      TDEV(1S): 1.096e-6
     TDEV(10S): 1.070e-6
    TDEV(100S): 1.200e-6
Realtime:
Reference: Realtime Source: Counter
Stability:
     TDEV(1mS): 2.208e-6
    TDEV(10mS): 2.223e-6
   TDEV(100mS): 2.249e-6
      TDEV(1S): 2.271e-6
     TDEV(10S): 4.224e-6
    TDEV(100S): 5.248e-5
Monotonic:
Reference: Monotonic Source: Counter
Stability:
     TDEV(1mS): 1.961e-6
    TDEV(10mS): 1.980e-6
   TDEV(100mS): 2.009e-6
      TDEV(1S): 2.050e-6
     TDEV(10S): 2.097e-6
    TDEV(100S): 5.205e-5
```

#### Server: Dual Xeon E5-2670 @ 2.60GHz
```
Calculating stability of time estimators... runtime ~15 minutes
Baseline:
Reference: Monotonic Source: Monotonic
Stability:
     TDEV(1mS): 3.506e-7
    TDEV(10mS): 3.530e-7
   TDEV(100mS): 3.554e-7
      TDEV(1S): 3.588e-7
     TDEV(10S): 3.581e-7
    TDEV(100S): 3.476e-7
Realtime:
Reference: Realtime Source: Counter
Stability:
     TDEV(1mS): 5.522e-7
    TDEV(10mS): 5.591e-7
   TDEV(100mS): 5.630e-7
      TDEV(1S): 5.717e-7
     TDEV(10S): 5.921e-7
    TDEV(100S): 1.258e-6
Monotonic:
Reference: Monotonic Source: Counter
Stability:
     TDEV(1mS): 5.829e-7
    TDEV(10mS): 5.868e-7
   TDEV(100mS): 5.959e-7
      TDEV(1S): 6.051e-7
     TDEV(10S): 6.173e-7
    TDEV(100S): 9.441e-7
```

**Comment by brayniac** [comment]
Awesome - sounds like it might work for you then. I clone the `Clocksource` and send it to worker threads for them to timestamp their own events - the struct is just holding the calibration constants and the enum to say which clocks to use. I think the idea of cloning and swapping it into the hot-path should work pretty well.

It might be possible to add some more to this library to periodically sync-up to the reference clock - maybe every N timestamps or every T seconds - I'll need to give more thought to that.

See if this works for you using this branch. If it seems like it does, I'll cleanup the branch and prepare to merge and release.

**Comment by brayniac** [comment]
@jonathanstrong - have you had a chance to test further?

**Comment by brayniac** [comment]
Changes are merged to master. To publish tonight
